language: node_js
deploy:
  provider: npm
  email: michael.heuberger@binarykitchen.com
  api_key:
    secure: YJ3ZUJRHKl6gG1byriwG5bqCNV0gJuA0n2J5Ob30QhJqhnT7Wdrm2M6aPTEPSn13wnO4k7Di/fj3NPtNiATKuR9nyHScTD0Ly1Lqn/vKblw1YHI2nto3VnPU8bqMUDjZGvio7LHUkAHv09Cs5lEHmlT0EWsH3oLhtPidIGd1jOI=
  on:
    repo: binarykitchen/wants-json
